### ISSUE TITLE
Windows 10 box takes an extra 1:35 minutes than required on the first boot

### ISSUE THREAD

**Issue by mahmoud-ashi** [gusztavvargadr/packer#181] opened 2020-03-22 21:20 UTC
"gusztavvargadr/windows-10" box spends 1:35 minutes on the first boot because of the first-time user preparation (The "Hi .. We're getting things ready for you .. This might take some minutes").
Host configuration:
- 32GB Memory
- Intel i7-8700K processor
- Ubuntu 18.04
VM configuration:
- Default configuration (1GB memory, 1CPU).

To have a better user experience, please boot up the VM in order to completely setup the machine before packing it. Thanks.

**Comment by gusztavvargadr** [comment] 2020-03-23 06:22
@mahmoud-ashi this is by design. Since this is an evaluation version of Windows 10, that expires after 90 days, it is packaged - including several reboots for e.g. doing Windows Updates - after doing a [Sysprep](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/sysprep--generalize--a-windows-installation) so this 90 days counter starts on the first boot, otherwise it would start at package time.

You can speed up the boot process by allocating more resources to the VM (I'd recommend at least 2 CPUs and 2 or 4 GB of memory for Windows 10). Please note, the Windows Server images boot a lot faster, if you don't necessarily need Windows 10.

**Comment by gusztavvargadr** [comment] 2020-03-27 18:32
@mahmoud-ashi I'm closing this but please feel free to reopen if you have any further questions.

**Closed by gusztavvargadr** 2020-03-27 18:32 UTC
Labels: question
