### ISSUE TITLE
Windows 10 2009.0.2012 Virtualbox box seems to be expired

### ISSUE THREAD

**Issue by malashi** [gusztavvargadr/packer#241] opened 2021-02-08 16:02 UTC
Hi @gusztavvargadr. Thanks again for maintaining those boxes! This has helped me a lot.
Recently (maybe 5 days ago), I noticed that the Windows 10 box is "dying" exactly 1 hour after it has booted. Looks like the windows 10 box (https://app.vagrantup.com/gusztavvargadr/boxes/windows-10/versions/2009.0.2012) shows that the license has expired on boot.

What I did:
- delete all boxes I have
- run command `vagrant init gusztavvargadr/windows-10 && vagrant up`

Here is a screenshot of the box once booted.
![image](https://user-images.githubusercontent.com/29478579/107245335-519a3580-6a2f-11eb-9d0d-8fdf47680c2d.png)

Here is also the event log just before the automatic shutdown.
![image](https://user-images.githubusercontent.com/29478579/107246613-b3a76a80-6a30-11eb-9173-ac8418da4c9c.png)

Could you please update the boxes. Thanks.

**Comment by gusztavvargadr** [comment] 2021-02-13 23:23
@malashi thanks for reaching out. I think the problems is not with the license but with the lack of activation.

My Windows boxes are built with Sysprep being invoked at the end of the build process, so that the activation counter for the evaluation versions start at the first boot of the machine instead of my build time. However, this results in activation being reset before the machine boots.

I can confirm that on the first boot boxes show the license expiration message, however, for me a single reboot solves the problem, and on the second boot it properly shows the 90 days expiration for Windows 10. You can also try invoking activation yourself under settings.

I'm planning to release new versions though within a couple of days and I will look into if I can automate better this part as part of the build or the boot process.

Please let me know if the above workaround works for you in the meantime.

**Comment by gusztavvargadr** [comment] 2021-02-25 01:46
@malashi any luck with this in the meantime? Did you have a change to try the above workarounds?

**Comment by mahmoud-ashi** [comment] 2021-02-25 11:47
Thanks @gusztavvargadr. The issue resolved on its own it seems if you wait like 5 mins after booting. In my case, I am using your box as base, provision it, then package it so that I can start booting from my box without needing to provision it again. In this case, vagrant will automatically do the reboot but that still did not seem to fix the issue imo. What solved is to keep it running for like 5 mins until the license refreshes. Do you know how to force refresh/start the license? Also, was there any changes on your side recently? Because I have been using your boxes for some time and this was the first time I see the issue. I later on faced similar issue with Windows server 2016.

**Comment by gusztavvargadr** [comment] 2021-04-08 10:12
@mahmoud-ashi I could not find a way yet to force this update, but I will try to implement this in one of the upcoming releases. Will close this now but please reopen if it still causes trouble.

**Closed by gusztavvargadr** 2021-04-08 10:12 UTC
Labels: support
