### ISSUE TITLE
c:\vagrant shared folder shows as Read-only

### ISSUE THREAD

**Issue by marcindulak** [gusztavvargadr/packer#135] opened 2019-09-04 19:17 UTC
https://app.vagrantup.com/gusztavvargadr/boxes/windows-10/versions/1903.0.1907 shows the following properties

![Screenshot from 2019-09-04 20-46-53](https://user-images.githubusercontent.com/3178318/64282654-3384f780-cf56-11e9-9a56-b17960a6d970.png)

Uncheck "Read-only" clicked "Apply", then "OK". The "Read-only" attribute restores itself when the folder is opened again. Interestingly, there are no problems with write access to the folder from the Windows guest, like creating subfolders or modifying files, and the changes are synchronized with the host.

An older software which relies on the attribute may break. 
Searching online it looks like this behavior on Windows 10 is often reported.

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

# http://stackoverflow.com/questions/23926945/specify-headless-or-gui-from-command-line
def gui_enabled?
  !ENV.fetch('GUI', '').empty?
end

Vagrant.configure(2) do |config|
  config.vm.define 'windows10' do |machine|
    machine.vm.box = 'gusztavvargadr/windows-10'
    machine.vm.box_url = machine.vm.box
    machine.vm.provider 'virtualbox' do |p|
      p.memory = 1536  # Windows is greedy
      p.cpus = 1
      p.gui = gui_enabled?
    end
  end
  config.vm.define "windows10" do |machine|
    # install chocolatey
    machine.vm.provision :shell, :inline => 'powershell -NoProfile -ExecutionPolicy unrestricted -Command "iex ((new-object net.webclient).DownloadString(\'https://chocolatey.org/install.ps1\'))"'
    machine.vm.provision :shell, :inline => '(Get-WmiObject Win32_ComputerSystem).Rename("windows10")'
    machine.vm.provision :shell, :inline => 'Restart-Computer -Force'
  end
end
```

```
cat /etc/*release | grep VERSION=
VERSION="18.04.3 LTS (Bionic Beaver)"
```

```
vboxmanage --version
5.2.32r132073
```

```
vagrant --version
Vagrant 2.2.5
```

```
 windows10: Guest Additions Version: 6.0.10
 windows10: VirtualBox Version: 5.2
```

**Comment by gusztavvargadr** [comment] 2019-09-04 21:31
@marcindulak thanks for reporting this, will take a look. In the meantime, is there any chance for you to test this with an up to date VirtualBox host?

**Comment by marcindulak** [comment] 2019-09-05 14:19
Isn't it the latest?

```
vagrant box update windows10
==> windows10: Checking for updates to 'gusztavvargadr/windows-10'
    windows10: Latest installed version: 1903.0.1907
    windows10: Version constraints: 
    windows10: Provider: virtualbox
==> windows10: Box 'gusztavvargadr/windows-10' (v1903.0.1907) is running the latest version.
```

I'm also confused about the versioning of the boxes - is every second one an "enterprise" version?

![Screenshot from 2019-09-05 16-18-15](https://user-images.githubusercontent.com/3178318/64350406-e148e280-cff8-11e9-9384-b74de1c0190c.png)

**Comment by gusztavvargadr** [comment] 2019-09-05 20:07
@marcindulak yeah sorry i meant `VirtualBox Version: 5.2`. It's well known as well to have compatibility issues if the host and the guest addition versions differ. I by default use the latest at the time of the creation of the box.

**Comment by gusztavvargadr** [comment] 2019-09-05 20:10
@marcindulak regarding the box versions, thanks for the feedback, as the descriptions say, one is simply the alias of the other. This makes more sense though for boxes where there are actually different "flavors" of the same version, see https://app.vagrantup.com/gusztavvargadr/boxes/windows-server for example, it is just the same pattern here.

If you have any suggestions about how to approach this better, please feel free to share, I have refactored already a few times the number and arrangement of boxes. Ideally, I want to keep the number of boxes stable, but also allow a pattern to handle different flavors (like editions) within them easily.

**Comment by marcindulak** [comment] 2019-09-06 16:36
The "Read-only" problem persists with the components as above, and

```
vboxmanage -version
6.0.12r133076
```

About the boxes, why https://app.vagrantup.com/gusztavvargadr/boxes/windows-10/versions/1903.0.1908-enterprise is not considered the latest and an alias created based on it?
On the screenshot above you can see this is the top listed windows-10 box.

**Comment by gusztavvargadr** [comment] 2019-09-06 17:26
@marcindulak ok, thanks for the details on the host versions.

There's a box with 1908, but it's in progress, currently being built and released (you can see it was recently created), I'm moving all the builds to Azure Pipelines and I'm currently in the middle of the process. Indeed, there will be another alias pointing to that soon.

**Comment by gusztavvargadr** [comment] 2019-09-08 21:40
@marcindulak it seems this is by design and nothing to do with Vagrant: https://superuser.com/a/1075797.

I double checked on my environments and `attrib` correctly shows files (even the folder) writeable.

I'm closing this now but please reopen if it causes any actual problems. In that case I'd probably try as well other synced folder types like `smb` or `rsync`.

**Closed by gusztavvargadr** 2019-09-08 21:40 UTC
Labels: question
